/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalFrame;

import emft_vol2.constants;
import emft_vol2.main_Jframe;
import java.util.ArrayList;
import javax.swing.JTextField;

/**
 *
 * @author Jozef
 */
public class BasicInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form BasicInfoPanel
     */
    public BasicInfoPanel() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_meno = new javax.swing.JLabel();
        jTextField_mano = new javax.swing.JTextField();
        jLabel_meno_projektu = new javax.swing.JLabel();
        jTextField_mano_projektu = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), language_internal_frame_basic_Info_Panel.LangLabel(constants.getLanguage_option(), 0)
            , javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP));

    jLabel_meno.setText(language_internal_frame_basic_Info_Panel.LangLabel(constants.getLanguage_option(), 1));

    jTextField_mano.setText(InternalFrameproject.Rozpätie.getMeno());
    jTextField_mano.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField_manoActionPerformed(evt);
        }
    });
    jTextField_mano.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            jTextField_manoKeyReleased(evt);
        }
    });

    jLabel_meno_projektu.setText(language_internal_frame_basic_Info_Panel.LangLabel(constants.getLanguage_option(), 2));

    jTextField_mano_projektu.setText(InternalFrameproject.Rozpätie.getMenoProjektu());
    jTextField_mano_projektu.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField_mano_projektuActionPerformed(evt);
        }
    });
    jTextField_mano_projektu.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            jTextField_mano_projektuKeyReleased(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel_meno_projektu, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jTextField_mano_projektu, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel_meno, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jTextField_mano, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(157, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField_mano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel_meno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField_mano_projektu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel_meno_projektu, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(17, Short.MAX_VALUE))
    );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_manoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_manoActionPerformed
        InternalFrameproject.Rozpätie.setMeno(jTextField_mano.getText());
    }//GEN-LAST:event_jTextField_manoActionPerformed

    private void jTextField_mano_projektuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_mano_projektuActionPerformed
        
    }//GEN-LAST:event_jTextField_mano_projektuActionPerformed

    private void jTextField_manoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_manoKeyReleased
       InternalFrameproject.Rozpätie.setMeno(jTextField_mano.getText());
    }//GEN-LAST:event_jTextField_manoKeyReleased

    public static JTextField getjTextField_mano() {
        return jTextField_mano;
    }

    public static void setjTextField_mano(JTextField jTextField_mano) {
        BasicInfoPanel.jTextField_mano = jTextField_mano;
    }

    public static JTextField getjTextField_mano_projektu() {
        return jTextField_mano_projektu;
    }

    public static void setjTextField_mano_projektu(JTextField jTextField_mano_projektu) {
        BasicInfoPanel.jTextField_mano_projektu = jTextField_mano_projektu;
    }

    private void jTextField_mano_projektuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_mano_projektuKeyReleased
       InternalFrameproject.Rozpätie.setMenoProjektu(jTextField_mano_projektu.getText());
    }//GEN-LAST:event_jTextField_mano_projektuKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_meno;
    private javax.swing.JLabel jLabel_meno_projektu;
    static javax.swing.JTextField jTextField_mano;
    static javax.swing.JTextField jTextField_mano_projektu;
    // End of variables declaration//GEN-END:variables
}

class language_internal_frame_basic_Info_Panel {

/**
 * Function just add elements to the array list 
 * If once function runs and sets variable "inicializovane" true it never runs again
 */    
static void constructor(){
              /*SK*/                /*CZ*/              /*EN*/   
 /*0*/   SK.add("Informácie o rozpätí");  
         CZ.add("MT3 software, SAG Elektrovod, autoři Jozef Bendík & Matej Cenký 2016 1.release"); 
         EN.add("MT3 software, SAG Elektrovod, created by Jozef Bendík & Matej Cenký 2016 1.release");                       //language String value  at position 
/*1*/    SK.add("Názov rozpätia :");  
         CZ.add("MT3 software, SAG Elektrovod, autoři Jozef Bendík & Matej Cenký 2016 1.release"); 
         EN.add("MT3 software, SAG Elektrovod, created by Jozef Bendík & Matej Cenký 2016 1.release"); 
/*2*/    SK.add("Názov projektu :");  
         CZ.add("MT3 software, SAG Elektrovod, autoři Jozef Bendík & Matej Cenký 2016 1.release"); 
         EN.add("MT3 software, SAG Elektrovod, created by Jozef Bendík & Matej Cenký 2016 1.release");  
/*3*/    SK.add("Nový projekt ");  
         CZ.add("MT3 software, SAG Elektrovod, autoři Jozef Bendík & Matej Cenký 2016 1.release"); 
         EN.add("MT3 software, SAG Elektrovod, created by Jozef Bendík & Matej Cenký 2016 1.release");  
                               
                        
                          
                
         
 // language_main_frame.LangLabel(constants.getLanguage_option(),0)      
 inicializovane = true;
}
 
/**
 * Function returns on string label in set language
 * @param X  defines the language 1 Slovak, 2 Czech, 3 English
 * @param Y  defines the label position according the drawing, is starts from 0 
 * @return 
 */
public static String LangLabel(int X,int Y){
    
    if ( inicializovane == false){constructor();}
    
    String SlovoDaloSlovo = "empty";
    switch (X) {
        case 1:  
            SlovoDaloSlovo=SK.get(Y);
            break;
        case 2:
            SlovoDaloSlovo=CZ.get(Y);
            break;
        case 3:
            SlovoDaloSlovo=EN.get(Y);
            break;
    }
    return SlovoDaloSlovo;
}    

public static String LangLabel2(){
 
    String SlovoDaloSlovo = "empty";
    
    return SlovoDaloSlovo;
    } 
 private static  final ArrayList<String> SK= new ArrayList<>();
 private static final ArrayList<String> CZ= new ArrayList<>();
 private static final ArrayList<String> EN= new ArrayList<>();
 private static boolean inicializovane = false;
}