/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emft_vol2;

import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JCheckBox;
import javax.swing.JTextField;
import tools.help;

/**
 *
 * @author Jozef
 */
public class calculation_Settings extends javax.swing.JFrame {

    /**
     * Creates new form about_JFrame
     */
    public calculation_Settings() {
        initComponents();
        seticon();
        setLocationRelativeTo(null);
        about_JframeIsOpen=true;
        presnostCH.setText(String.valueOf(constants.getPresnostCH()));
        divergencia.setText(String.valueOf(constants.getDivergencia_pocet()));
         addWindowListener(new WindowAdapter() // listener na krizik zabretie okna
        {
            @Override
            public void windowClosing(WindowEvent e)
            {
                about_JframeIsOpen= false;
                e.getWindow().dispose();
            }
        });
        
    }
     private void seticon() {
     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/graphics/" + "icon.png")));
    }
    public static JCheckBox getEmirrorA() {
        return EmirrorA;
    }

    public static void setEmirrorA(JCheckBox EmirrorA) {
        calculation_Settings.EmirrorA = EmirrorA;
    }

    public static JCheckBox getEmirrorB() {
        return EmirrorB;
    }

    public static void setEmirrorB(JCheckBox EmirrorB) {
        calculation_Settings.EmirrorB = EmirrorB;
    }

    public static JCheckBox getEmirrorOff() {
        return EmirrorOff;
    }

    public static void setEmirrorOff(JCheckBox EmirrorOff) {
        calculation_Settings.EmirrorOff = EmirrorOff;
    }

    public static JCheckBox getEmod() {
        return Emod;
    }

    public static void setEmod(JCheckBox Emod) {
        calculation_Settings.Emod = Emod;
    }

    public static JCheckBox getI() {
        return I;
    }

    public static void setI(JCheckBox I) {
        calculation_Settings.I = I;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EmirrorA = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        EmirrorB = new javax.swing.JCheckBox();
        EmirrorOff = new javax.swing.JCheckBox();
        I = new javax.swing.JCheckBox();
        Emod = new javax.swing.JCheckBox();
        presnostCH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        divergencia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PhiIplus = new javax.swing.JTextField();
        PhisUplus = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        if(constants.getLanguage_option() ==1){
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/header_nastaveniaV_SK.png")));
        }
        if(constants.getLanguage_option() ==3){
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/header_nastaveniaV_EN.png"))); // NOI18N
        }
        if(constants.getLanguage_option() ==2){
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/header_nastaveniaV_CZ.png"))); // NOI18N
        }

        jLabel2.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 19));

        buttonGroup1.add(EmirrorA);
        EmirrorA.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 20));
        EmirrorA.setToolTipText(language_main_frame.LangLabel(constants.getLanguage_option(), 22));
        EmirrorA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmirrorAActionPerformed(evt);
            }
        });

        jLabel3.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 18));

        buttonGroup1.add(EmirrorB);
        EmirrorB.setSelected(true);
        EmirrorB.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 21));
        EmirrorB.setToolTipText(language_main_frame.LangLabel(constants.getLanguage_option(), 23));
        EmirrorB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmirrorBActionPerformed(evt);
            }
        });

        buttonGroup1.add(EmirrorOff);
        EmirrorOff.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 24));
        EmirrorOff.setToolTipText(language_main_frame.LangLabel(constants.getLanguage_option(), 25));
        EmirrorOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmirrorOffActionPerformed(evt);
            }
        });

        I.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 61));
        I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IActionPerformed(evt);
            }
        });

        buttonGroup2.add(Emod);
        Emod.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 62));
        Emod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmodActionPerformed(evt);
            }
        });

        presnostCH.setText("jTextField1");
        presnostCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presnostCHActionPerformed(evt);
            }
        });
        presnostCH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                presnostCHKeyReleased(evt);
            }
        });

        jLabel4.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 63));
        jLabel4.setToolTipText(language_main_frame.LangLabel(constants.getLanguage_option(), 64));

        divergencia.setText("jTextField1");
        divergencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                divergenciaKeyReleased(evt);
            }
        });

        jLabel5.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 65));
        jLabel5.setToolTipText(language_main_frame.LangLabel(constants.getLanguage_option(), 66));

        PhiIplus.setText("0");
        PhiIplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhiIplusActionPerformed(evt);
            }
        });
        PhiIplus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PhiIplusKeyReleased(evt);
            }
        });

        PhisUplus.setText("0");
        PhisUplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhisUplusActionPerformed(evt);
            }
        });
        PhisUplus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PhisUplusKeyReleased(evt);
            }
        });

        jLabel6.setText("Phi U plus");
        jLabel5.setToolTipText(language_main_frame.LangLabel(constants.getLanguage_option(), 66));

        jLabel7.setText("Phi I plus");
        jLabel4.setToolTipText(language_main_frame.LangLabel(constants.getLanguage_option(), 64));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(I, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Emod, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(44, 44, 44))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(EmirrorOff, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(EmirrorA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                                .addComponent(EmirrorB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(87, 87, 87)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(divergencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(PhiIplus)
                                            .addComponent(PhisUplus)
                                            .addComponent(presnostCH))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 49, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(EmirrorA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmirrorB))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmirrorOff))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhiIplus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhisUplus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(I)
                    .addComponent(presnostCH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Emod)
                    .addComponent(divergencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmirrorAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmirrorAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmirrorAActionPerformed

    private void EmirrorBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmirrorBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmirrorBActionPerformed

    private void EmirrorOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmirrorOffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmirrorOffActionPerformed

    private void IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IActionPerformed

    private void EmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmodActionPerformed

    private void presnostCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presnostCHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_presnostCHActionPerformed

    private void presnostCHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_presnostCHKeyReleased
         constants.setPresnostCH( help.ReadCheckDouble(presnostCH , 0.0001));
    }//GEN-LAST:event_presnostCHKeyReleased

    private void divergenciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_divergenciaKeyReleased
       constants.setDivergencia_pocet((int)help.ReadCheckDouble(divergencia ,10));
    }//GEN-LAST:event_divergenciaKeyReleased

    private void PhiIplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhiIplusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhiIplusActionPerformed

    private void PhiIplusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PhiIplusKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_PhiIplusKeyReleased

    private void PhisUplusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PhisUplusKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_PhisUplusKeyReleased

    private void PhisUplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhisUplusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhisUplusActionPerformed

   static  public JTextField getPhiIplus() {
        return PhiIplus;
    }

    public void setPhiIplus(JTextField PhiIplus) {
        this.PhiIplus = PhiIplus;
    }

    static public JTextField getPhisUplus() {
        return PhisUplus;
    }

    public void setPhisUplus(JTextField PhisUplus) {
        this.PhisUplus = PhisUplus;
    }

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculation_Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculation_Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculation_Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculation_Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculation_Settings().setVisible(true);
            }
        });
         
    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JCheckBox EmirrorA;
    private static javax.swing.JCheckBox EmirrorB;
    private static javax.swing.JCheckBox EmirrorOff;
    private static javax.swing.JCheckBox Emod;
    private static javax.swing.JCheckBox I;
    private static javax.swing.JTextField PhiIplus;
    private static javax.swing.JTextField PhisUplus;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField divergencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField presnostCH;
    // End of variables declaration//GEN-END:variables
    public static boolean about_JframeIsOpen;

    
}
