/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emft_vol2;

import tools.help;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Jozef
 */
public class constants_Jframe extends javax.swing.JFrame {

   

    /**
     * Creates new form constants_Jframe
     */
    public constants_Jframe() {
        initComponents();
        seticon();
        setLocationRelativeTo(null); // poloha okna na stred
        constants_JframeIsOpen= true; // ak je otvorene okno da sa true ak nie da sa false je to kontrola pre vyvolavaci Jframe
        addWindowListener(new WindowAdapter() // listener na krizik zabretie okna
        {
            @Override
            public void windowClosing(WindowEvent e)
            {
                constants_JframeIsOpen= false;
                e.getWindow().dispose();
            }
        });
        
        //inicializacia default hodnot
        help.DisplayDouble(jTextField_Freq, constants.getFrequency(), 2);
        help.DisplayDouble(jTextField_epsi1, constants.getEpsi1(), 2);
        help.DisplayDouble(jTextField_mu1, constants.getMu1(), 2);
        help.DisplayDouble(jTextField_Brms, constants.getAkcneB()*1000000, 2);
        help.DisplayDouble(jTextField_erms, constants.getAkcneE(), 2);
        help.DisplayDouble(jTextField_Irms, constants.getAkcneI(), 2);
        help.DisplayDouble(jTextField_Emodrms, constants.getAkcneEmod(), 2);
        help.DisplayDouble(jTextField_KEI, constants.getKE_I(), 2);
        help.DisplayDouble(jTextField_KbI, constants.getKE_I(), 2);
        help.DisplayDouble(jTextField_KE_emod, constants.getKE_Emod(), 2);
        help.DisplayDouble(jTextField_Kb_emod, constants.getKB_Emod(), 2);
        help.DisplayDouble(jTextField_sigma, constants.getSigma(), 2);
       // help.DisplayDouble(jTextField_DN, constants.getDN(), 2);
     //   help.DisplayDouble(jTextField_GCX, constants.getGCcoordinates()[0], 2);
     //   help.DisplayDouble(jTextField_GCZ, constants.getGCcoordinates()[2], 2);
        
        
    }
      
    
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_Freq = new javax.swing.JTextField();
        jLabel_freq = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_mu1 = new javax.swing.JTextField();
        jLabel_mu1 = new javax.swing.JLabel();
        jTextField_epsi1 = new javax.swing.JTextField();
        jLabel_epsi1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_Brms = new javax.swing.JTextField();
        jLabel_Brms = new javax.swing.JLabel();
        jLabel_erms = new javax.swing.JLabel();
        jTextField_erms = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton_saveupdateDAT = new javax.swing.JButton();
        jButton_cancel = new javax.swing.JButton();
        jButton_save = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel_mu2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_KEI = new javax.swing.JTextField();
        jLabel_KBI = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_KbI = new javax.swing.JTextField();
        jLabel_KEEMOD = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField_KE_emod = new javax.swing.JTextField();
        jLabel_KBEMOD = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_Kb_emod = new javax.swing.JTextField();
        jLabel_Irms = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField_Irms = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel_emodrms = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField_Emodrms = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel_KBI1 = new javax.swing.JLabel();
        jTextField_sigma = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTextField_Freq.setText("jTextField1");
        jTextField_Freq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FreqActionPerformed(evt);
            }
        });
        jTextField_Freq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_FreqKeyReleased(evt);
            }
        });

        jLabel_freq.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_freq.setText(language_cosntant_frame.LangLabel(constants.getLanguage_option(),0) );

        if(constants.getLanguage_option() ==1){
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/header_constants_SK.png"))); // NOI18N
        }
        if(constants.getLanguage_option() ==3){
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/header_constants_EN.png"))); // NOI18N
        }
        if(constants.getLanguage_option() ==2){
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/header_constants_CZ.png"))); // NOI18N
        }

        jLabel2.setText("Hz");

        jTextField_mu1.setText("jTextField1");
        jTextField_mu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_mu1ActionPerformed(evt);
            }
        });
        jTextField_mu1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_mu1KeyReleased(evt);
            }
        });

        jLabel_mu1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_mu1.setText(language_cosntant_frame.LangLabel(constants.getLanguage_option(),1) );

        jTextField_epsi1.setText("jTextField1");
        jTextField_epsi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_epsi1ActionPerformed(evt);
            }
        });
        jTextField_epsi1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_epsi1KeyReleased(evt);
            }
        });

        jLabel_epsi1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_epsi1.setText(language_cosntant_frame.LangLabel(constants.getLanguage_option(),2) );

        jLabel3.setText("muT ");

        jTextField_Brms.setText("jTextField1");
        jTextField_Brms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_BrmsActionPerformed(evt);
            }
        });
        jTextField_Brms.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_BrmsKeyReleased(evt);
            }
        });

        jLabel_Brms.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Brms.setText(language_cosntant_frame.LangLabel(constants.getLanguage_option(),3) );

        jLabel_erms.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_erms.setText(language_cosntant_frame.LangLabel(constants.getLanguage_option(),4) );

        jTextField_erms.setText("jTextField1");
        jTextField_erms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ermsActionPerformed(evt);
            }
        });
        jTextField_erms.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_ermsKeyReleased(evt);
            }
        });

        jLabel4.setText("V/m");

        jButton_saveupdateDAT.setText(language_cosntant_frame.LangLabel(constants.getLanguage_option(),5) );
        jButton_saveupdateDAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveupdateDATActionPerformed(evt);
            }
        });

        jButton_cancel.setText(language_cosntant_frame.LangLabel(constants.getLanguage_option(),7) );
        jButton_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelActionPerformed(evt);
            }
        });

        jButton_save.setText(language_cosntant_frame.LangLabel(constants.getLanguage_option(),6) );
        jButton_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveActionPerformed(evt);
            }
        });

        jLabel5.setText("=");

        jLabel6.setText("=");

        jLabel7.setText("=");

        jLabel8.setText("=");

        jLabel9.setText("=");

        jLabel14.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 60));

        jLabel_mu2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_mu2.setText("Ke I");

        jLabel10.setText("=");

        jTextField_KEI.setText("jTextField1");
        jTextField_KEI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_KEIActionPerformed(evt);
            }
        });
        jTextField_KEI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_KEIKeyReleased(evt);
            }
        });

        jLabel_KBI.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_KBI.setText("Kb I");

        jLabel11.setText("=");

        jTextField_KbI.setText("jTextField1");
        jTextField_KbI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_KbIActionPerformed(evt);
            }
        });
        jTextField_KbI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_KbIKeyReleased(evt);
            }
        });

        jLabel_KEEMOD.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_KEEMOD.setText("Ke Emod ");

        jLabel12.setText("=");

        jTextField_KE_emod.setText("jTextField1");
        jTextField_KE_emod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_KE_emodActionPerformed(evt);
            }
        });
        jTextField_KE_emod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_KE_emodKeyReleased(evt);
            }
        });

        jLabel_KBEMOD.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_KBEMOD.setText("Kb Emod");

        jLabel13.setText("=");

        jTextField_Kb_emod.setText("jTextField1");
        jTextField_Kb_emod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Kb_emodActionPerformed(evt);
            }
        });
        jTextField_Kb_emod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Kb_emodKeyReleased(evt);
            }
        });

        jLabel_Irms.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Irms.setText(language_cosntant_frame.LangLabel(constants.getLanguage_option(),3) );

        jLabel15.setText("=");

        jTextField_Irms.setText("jTextField1");
        jTextField_Irms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IrmsActionPerformed(evt);
            }
        });
        jTextField_Irms.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_IrmsKeyReleased(evt);
            }
        });

        jLabel16.setText("A/m2");

        jLabel_emodrms.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_emodrms.setText(language_cosntant_frame.LangLabel(constants.getLanguage_option(),4) );

        jLabel17.setText("=");

        jTextField_Emodrms.setText("jTextField1");
        jTextField_Emodrms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EmodrmsActionPerformed(evt);
            }
        });
        jTextField_Emodrms.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_EmodrmsKeyReleased(evt);
            }
        });

        jLabel18.setText("V/m");

        jLabel_KBI1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_KBI1.setText("sigma");

        jTextField_sigma.setText("jTextField1");
        jTextField_sigma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_sigmaActionPerformed(evt);
            }
        });
        jTextField_sigma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_sigmaKeyReleased(evt);
            }
        });

        jLabel19.setText("=");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_save, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_saveupdateDAT, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator3)
                                .addGap(107, 107, 107))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel_freq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel_mu1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel_Brms, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField_Brms, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jTextField_mu1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(20, 20, 20))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel5)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTextField_Freq, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel2))))
                                        .addGap(13, 13, 13)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel_epsi1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField_epsi1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel_erms, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField_erms, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel4))))
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel_Irms, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_Irms, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16)
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel_emodrms, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_Emodrms, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel_KBI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField_KbI, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel_mu2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField_KEI, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_KBI1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_sigma, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_KEEMOD, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_KBEMOD, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_KE_emod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Kb_emod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_Freq, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_freq, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_mu1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_mu1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_epsi1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_epsi1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Brms, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Brms, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_erms, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_erms, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Irms, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Irms, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_emodrms, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Emodrms, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_saveupdateDAT)
                    .addComponent(jButton_save)
                    .addComponent(jButton_cancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_mu2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_KEI, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_KEEMOD, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_KE_emod, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_KBI, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_KbI, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Kb_emod, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_KBEMOD, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_KBI1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_sigma, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_FreqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FreqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FreqActionPerformed

    private void jTextField_mu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_mu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_mu1ActionPerformed

    private void jTextField_epsi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_epsi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_epsi1ActionPerformed

    private void jTextField_BrmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_BrmsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_BrmsActionPerformed

    private void jTextField_ermsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ermsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ermsActionPerformed

    private void jTextField_FreqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_FreqKeyReleased
       constants.setFrequency( help.ReadCheckDouble(jTextField_Freq, -1));
        
    }//GEN-LAST:event_jTextField_FreqKeyReleased

    private void jTextField_mu1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_mu1KeyReleased
       constants.setMu1(help.ReadCheckDouble(jTextField_mu1, -1));
    }//GEN-LAST:event_jTextField_mu1KeyReleased

    private void jTextField_BrmsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_BrmsKeyReleased
       constants.setAkcneB( help.ReadCheckDouble(jTextField_Brms, -1));
    }//GEN-LAST:event_jTextField_BrmsKeyReleased

    private void jTextField_epsi1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_epsi1KeyReleased
        constants.setEpsi1(help.ReadCheckDouble(jTextField_epsi1, -1));
    }//GEN-LAST:event_jTextField_epsi1KeyReleased

    private void jTextField_ermsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ermsKeyReleased
        constants.setAkcneE(help.ReadCheckDouble(jTextField_erms, -1));
    }//GEN-LAST:event_jTextField_ermsKeyReleased

    private void jButton_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveActionPerformed
        saveToConstants();
        constants_JframeIsOpen=false;
        dispose();
    }//GEN-LAST:event_jButton_saveActionPerformed

    private void jButton_saveupdateDATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveupdateDATActionPerformed
        saveToConstants();
        try { // update in databaze
            
           
            
            constants.UpdateConstant("Freq", 1, constants.getFrequency());
            constants.UpdateConstant("Mu1", 1, constants.getMu1());
            constants.UpdateConstant("Epsi1", 1, constants.getEpsi1());
            constants.UpdateConstant("AkcneE", 1, constants.getAkcneE());
            constants.UpdateConstant("AkcneB", 1, constants.getAkcneB());
            constants.UpdateConstant("DN", 1, constants.getDN());
            constants.UpdateConstant("GC_X", 1, constants.getGCcoordinates()[0]);
            constants.UpdateConstant("GC_Z", 1, constants.getGCcoordinates()[2]);
            constants.UpdateConstant("Mu0", 1, constants.getMu0());
          
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(constants_Jframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        constants_JframeIsOpen=false;
        
        dispose();
    }//GEN-LAST:event_jButton_saveupdateDATActionPerformed

    private void jButton_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelActionPerformed
       constants_JframeIsOpen=false;
       dispose();
    }//GEN-LAST:event_jButton_cancelActionPerformed

    private void jTextField_KEIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_KEIActionPerformed
        
    }//GEN-LAST:event_jTextField_KEIActionPerformed

    private void jTextField_KEIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_KEIKeyReleased
        constants.setKE_I( help.ReadCheckDouble(jTextField_KEI , 60));
    }//GEN-LAST:event_jTextField_KEIKeyReleased

    private void jTextField_KbIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_KbIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_KbIActionPerformed

    private void jTextField_KbIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_KbIKeyReleased
        constants.setKB_I(help.ReadCheckDouble(jTextField_KbI , 60));
    }//GEN-LAST:event_jTextField_KbIKeyReleased

    private void jTextField_KE_emodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_KE_emodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_KE_emodActionPerformed

    private void jTextField_KE_emodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_KE_emodKeyReleased
        constants.setKE_Emod(help.ReadCheckDouble(jTextField_KE_emod , 60));
    }//GEN-LAST:event_jTextField_KE_emodKeyReleased

    private void jTextField_Kb_emodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Kb_emodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Kb_emodActionPerformed

    private void jTextField_Kb_emodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Kb_emodKeyReleased
       constants.setKB_Emod(help.ReadCheckDouble(jTextField_Kb_emod , 60));
    }//GEN-LAST:event_jTextField_Kb_emodKeyReleased

    private void jTextField_IrmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IrmsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IrmsActionPerformed

    private void jTextField_IrmsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IrmsKeyReleased
        constants.setAkcneI(help.ReadCheckDouble(jTextField_Irms , 2));
    }//GEN-LAST:event_jTextField_IrmsKeyReleased

    private void jTextField_EmodrmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EmodrmsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EmodrmsActionPerformed

    private void jTextField_EmodrmsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_EmodrmsKeyReleased
        constants.setAkcneEmod(help.ReadCheckDouble(jTextField_Emodrms , 0.2));
    }//GEN-LAST:event_jTextField_EmodrmsKeyReleased

    private void jTextField_sigmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_sigmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_sigmaActionPerformed

    private void jTextField_sigmaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_sigmaKeyReleased
        constants.setSigma(help.ReadCheckDouble(jTextField_sigma , 0.2));
    }//GEN-LAST:event_jTextField_sigmaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(constants_Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(constants_Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(constants_Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(constants_Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new constants_Jframe().setVisible(true);
                
            }
            
            
            
        });
    }

    public JTextField getjTextField_Emodrms() {
        return jTextField_Emodrms;
    }

    public void setjTextField_Emodrms(JTextField jTextField_Emodrms) {
        this.jTextField_Emodrms = jTextField_Emodrms;
    }

    public JTextField getjTextField_Irms() {
        return jTextField_Irms;
    }

    public void setjTextField_Irms(JTextField jTextField_Irms) {
        this.jTextField_Irms = jTextField_Irms;
    }

    public JTextField getjTextField_KEI() {
        return jTextField_KEI;
    }

    public void setjTextField_KEI(JTextField jTextField_KEI) {
        this.jTextField_KEI = jTextField_KEI;
    }

    public JTextField getjTextField_KE_emod() {
        return jTextField_KE_emod;
    }

    public void setjTextField_KE_emod(JTextField jTextField_KE_emod) {
        this.jTextField_KE_emod = jTextField_KE_emod;
    }

    public JTextField getjTextField_KbI() {
        return jTextField_KbI;
    }

    public void setjTextField_KbI(JTextField jTextField_KbI) {
        this.jTextField_KbI = jTextField_KbI;
    }

    public JTextField getjTextField_Kb_emod() {
        return jTextField_Kb_emod;
    }

    public void setjTextField_Kb_emod(JTextField jTextField_Kb_emod) {
        this.jTextField_Kb_emod = jTextField_Kb_emod;
    }
    
    private void seticon() {
     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/graphics/" + "icon.png")));
    }
    private void saveToConstants(){
        constants.setFrequency(help.ReadCheckDouble(jTextField_Freq, -1));
        constants.setMu1(help.ReadCheckDouble(jTextField_mu1, -1));
        constants.setEpsi1(help.ReadCheckDouble(jTextField_epsi1, -1));
        constants.setAkcneB(help.ReadCheckDouble(jTextField_Brms, -1)/1000000);
        constants.setAkcneE(help.ReadCheckDouble(jTextField_erms, -1));
      //  constants.setDN(help.ReadCheckDouble(jTextField_DN, -1));
      //  constants.setGCcoordinates(help.ReadCheckDouble(jTextField_GCX, -1),0);
      //  constants.setGCcoordinates(help.ReadCheckDouble(jTextField_GCZ, -1),2);
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JButton jButton_save;
    private javax.swing.JButton jButton_saveupdateDAT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Brms;
    private javax.swing.JLabel jLabel_Irms;
    private javax.swing.JLabel jLabel_KBEMOD;
    private javax.swing.JLabel jLabel_KBI;
    private javax.swing.JLabel jLabel_KBI1;
    private javax.swing.JLabel jLabel_KEEMOD;
    private javax.swing.JLabel jLabel_emodrms;
    private javax.swing.JLabel jLabel_epsi1;
    private javax.swing.JLabel jLabel_erms;
    private javax.swing.JLabel jLabel_freq;
    private javax.swing.JLabel jLabel_mu1;
    private javax.swing.JLabel jLabel_mu2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField_Brms;
    private javax.swing.JTextField jTextField_Emodrms;
    private javax.swing.JTextField jTextField_Freq;
    private javax.swing.JTextField jTextField_Irms;
    private javax.swing.JTextField jTextField_KEI;
    private javax.swing.JTextField jTextField_KE_emod;
    private javax.swing.JTextField jTextField_KbI;
    private javax.swing.JTextField jTextField_Kb_emod;
    private javax.swing.JTextField jTextField_epsi1;
    private javax.swing.JTextField jTextField_erms;
    private javax.swing.JTextField jTextField_mu1;
    private javax.swing.JTextField jTextField_sigma;
    // End of variables declaration//GEN-END:variables
    public static boolean constants_JframeIsOpen;

}


/**
 *
 * @author xbendikj
 */
class language_cosntant_frame {

/**
 * Function just add elements to the array list 
 * If once function runs and sets variable "inicializovane" true it never runs again
 */    
static void constructor(){
              /*SK*/                /*CZ*/              /*EN*/   
 /*0*/   SK.add("Frekvencia");  
         CZ.add("MT3 software, SAG Elektrovod, autoři Jozef Bendík & Matej Cenký 2016 1.release"); 
         EN.add("MT3 software, SAG Elektrovod, created by Jozef Bendík & Matej Cenký 2016 1.release");                       //language String value  at position 
 /*1*/   SK.add("\u03BC\u2081");  
         CZ.add("MT3 software, SAG Elektrovod, autoři Jozef Bendík & Matej Cenký 2016 1.release"); 
         EN.add("MT3 software, SAG Elektrovod, created by Jozef Bendík & Matej Cenký 2016 1.release");                       //language String value  at position 
 /*2*/   SK.add("\u03B5\u2081");   
         CZ.add("MT3 software, SAG Elektrovod, autoři Jozef Bendík & Matej Cenký 2016 1.release"); 
         EN.add("MT3 software, SAG Elektrovod, created by Jozef Bendík & Matej Cenký 2016 1.release");                       //language String value  at position 
 /*3*/   SK.add("Brms - limit");  //   ze vraj rms \u1D63\u2098\u209B
         CZ.add("MT3 software, SAG Elektrovod, autoři Jozef Bendík & Matej Cenký 2016 1.release"); 
         EN.add("MT3 software, SAG Elektrovod, created by Jozef Bendík & Matej Cenký 2016 1.release");                       //language String value  at position 
  /*4*/  SK.add("Erms - limitt");  
         CZ.add("MT3 software, SAG Elektrovod, autoři Jozef Bendík & Matej Cenký 2016 1.release"); 
         EN.add("MT3 software, SAG Elektrovod, created by Jozef Bendík & Matej Cenký 2016 1.release"); 
  /*5*/  SK.add("Uložiť permanentne");  
         CZ.add("MT3 software, SAG Elektrovod, autoři Jozef Bendík & Matej Cenký 2016 1.release"); 
         EN.add("MT3 software, SAG Elektrovod, created by Jozef Bendík & Matej Cenký 2016 1.release"); //language String value  at position 
  /*6*/  SK.add("Uložiť");  
         CZ.add("MT3 software, SAG Elektrovod, autoři Jozef Bendík & Matej Cenký 2016 1.release"); 
         EN.add("MT3 software, SAG Elektrovod, created by Jozef Bendík & Matej Cenký 2016 1.release");                       //language String value  at position              
  /*7*/  SK.add("Zrušiť");  
         CZ.add("MT3 software, SAG Elektrovod, autoři Jozef Bendík & Matej Cenký 2016 1.release"); 
         EN.add("MT3 software, SAG Elektrovod, created by Jozef Bendík & Matej Cenký 2016 1.release");                       //language String value  at position 
  /*8*/  SK.add("\u0394N");  
         CZ.add("MT3 software, SAG Elektrovod, autoři Jozef Bendík & Matej Cenký 2016 1.release"); 
         EN.add("MT3 software, SAG Elektrovod, created by Jozef Bendík & Matej Cenký 2016 1.release");                       //language String value  at position 
  /*9*/  SK.add("G.C. x");  
         CZ.add("MT3 software, SAG Elektrovod, autoři Jozef Bendík & Matej Cenký 2016 1.release"); 
         EN.add("MT3 software, SAG Elektrovod, created by Jozef Bendík & Matej Cenký 2016 1.release");                       //language String value  at position 
  /*10*/  SK.add("G.C. z");  
         CZ.add("MT3 software, SAG Elektrovod, autoři Jozef Bendík & Matej Cenký 2016 1.release"); 
         EN.add("MT3 software, SAG Elektrovod, created by Jozef Bendík & Matej Cenký 2016 1.release");                       //language String value  at position 
                                               
         
         
 // language_cosntant_frame.LangLabel(constants.getLanguage_option(),0)      
 inicializovane = true;
}
 
/**
 * Function returns on string label in set language
 * @param X  defines the language 1 Slovak, 2 Czech, 3 English
 * @param Y  defines the label position according the drawing, is starts from 0 
 * @return 
 */
public static String LangLabel(int X,int Y){
    
    if ( inicializovane == false){constructor();}
    
    String SlovoDaloSlovo = "empty";
    switch (X) {
        case 1:  
            SlovoDaloSlovo=SK.get(Y);
            break;
        case 2:
            SlovoDaloSlovo=CZ.get(Y);
            break;
        case 3:
            SlovoDaloSlovo=EN.get(Y);
            break;
    }
    return SlovoDaloSlovo;
}    

public static String LangLabel2(){
 
    String SlovoDaloSlovo = "empty";
    
    return SlovoDaloSlovo;
    } 
 private static  final ArrayList<String> SK= new ArrayList<>();
 private static final ArrayList<String> CZ= new ArrayList<>();
 private static final ArrayList<String> EN= new ArrayList<>();
 private static boolean inicializovane = false;
}