/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emft_vol2;

import dislin.plot_1D;
import dislin.plot_2D;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JTextField;
import tools.help;

/**
 *
 * @author Jozef
 */
public class Dislin_Settings extends javax.swing.JFrame {

    /**
     * Creates new form about_JFrame
     */
    public Dislin_Settings() {
        initComponents();
        seticon();
        setLocationRelativeTo(null);
        jTextField_stepX.setText(String.valueOf(constants.getDislin_Step_between_the_labels_X()));
        jTextField_stepY.setText(String.valueOf(constants.getDislin_Step_between_the_labels_Y()));
        jTextField_stepZ.setText(String.valueOf(constants.getDislin_Step_between_the_labels_Z()));
        
        jTextField_sizeX.setText(String.valueOf(constants.getDislin_velkost_strany_X()));
        jTextField_sizeY.setText(String.valueOf(constants.getDislin_velkost_strany_Y()));
        
        jTextField_hrubkaTA.setText(String.valueOf(constants.getDislin_velkost_textu_pred_grafom()));
        jTextField_hrubkaTB.setText(String.valueOf(constants.getDislin_velkost_textu_za_grafom()));
        
        jTextField_hrubkaCA.setText(String.valueOf(constants.getDislin_hrubka_ciar_pred_grafom()));
        jTextField_hrubkaCB.setText(String.valueOf(constants.getDislin_hrubka_ciar_za_grafom()));
        
        jTextField_grid.setText(String.valueOf(constants.getDislin_hrubka_ciar_GRID()));
        about_JframeIsOpen=true;
        
        jTextField_nasUP.setText(String.valueOf(constants.getDislin_graph_nasobok_z_vrchu()));
        jTextField_nasDown.setText(String.valueOf(constants.getDislin_graph_nasobok_z_spodu()));
        jTextField_nassides.setText(String.valueOf(constants.getDislin_graph_nasobok_zo_stran()));
        
        jTextField_popisX.setText(String.valueOf(constants.getDislin_Label_X()));
        jTextField_popisY.setText(String.valueOf(constants.getDislin_Label_Y()));
        jTextField_popisZ.setText(String.valueOf(constants.getDislin_Label_Z()));
        
        grid.setSelected(constants.isDislin_grid());
        grid1.setSelected(constants.isDislin_graph_bgcol());
       noZA.setSelected(constants.isDislin_nozeroYA());
        jTextField_pockon.setText(String.valueOf(constants.getDislin_pocet_kontur()));
        jTextField_pocdes.setText(String.valueOf(constants.getDislin_pocet_des_miest()));
        ROW1.setText( language_main_frame.LangLabel(constants.getLanguage_option(), 0));
        ROW2.setText( " ");
         addWindowListener(new WindowAdapter() // listener na krizik zabretie okna
        {
            @Override
            public void windowClosing(WindowEvent e)
            {
                about_JframeIsOpen= false;
                e.getWindow().dispose();
            }
        });
        
    }

    

    public static void setEmirrorOff(JCheckBox EmirrorOff) {
        Dislin_Settings.grid = EmirrorOff;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        grid = new javax.swing.JCheckBox();
        jTextField_hrubkaCA = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField_hrubkaCB = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_popisX = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField_popisY = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField_popisZ = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        grid1 = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jTextField_pocdes = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField_sizeX = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_sizeY = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_stepX = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_stepZ = new javax.swing.JTextField();
        jTextField_stepY = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField_hrubkaTA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_hrubkaTB = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_grid = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField_nasUP = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField_nasDown = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField_nassides = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField_pockon = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        ROW1 = new javax.swing.JTextField();
        ROW2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        noZA = new javax.swing.JCheckBox();
        RAIN = new javax.swing.JCheckBox();
        TEMP = new javax.swing.JCheckBox();
        BW = new javax.swing.JCheckBox();
        COL2 = new javax.swing.JCheckBox();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ZcaleMax = new javax.swing.JTextField();
        ZscaleMin = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        AXtype = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        if(constants.getLanguage_option() ==1){
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/header_Dislin_SK.png")));
        }
        if(constants.getLanguage_option() ==3){
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/header_Dislin_SK.png"))); // NOI18N
        }
        if(constants.getLanguage_option() ==2){
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/header_Dislin_SK.png"))); // NOI18N
        }

        jLabel3.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 26));

        grid.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 54));
        grid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gridActionPerformed(evt);
            }
        });

        jTextField_hrubkaCA.setText("jTextField1");
        jTextField_hrubkaCA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_hrubkaCAKeyReleased(evt);
            }
        });

        jLabel10.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 39));
        jLabel10.setToolTipText(language_main_frame.LangLabel(constants.getLanguage_option(), 40));

        jTextField_hrubkaCB.setText("jTextField1");
        jTextField_hrubkaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_hrubkaCBActionPerformed(evt);
            }
        });
        jTextField_hrubkaCB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_hrubkaCBKeyReleased(evt);
            }
        });

        jLabel11.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 41));
        jLabel11.setToolTipText(language_main_frame.LangLabel(constants.getLanguage_option(), 42));

        jTextField_popisX.setText("jTextField1");
        jTextField_popisX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_popisXKeyReleased(evt);
            }
        });

        jLabel16.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 50));
        jLabel16.setToolTipText(language_main_frame.LangLabel(constants.getLanguage_option(), 53));

        jTextField_popisY.setText("jTextField1");
        jTextField_popisY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_popisYKeyReleased(evt);
            }
        });

        jLabel17.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 51));
        jLabel17.setToolTipText(language_main_frame.LangLabel(constants.getLanguage_option(), 53));

        jTextField_popisZ.setText("jTextField1");
        jTextField_popisZ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_popisZKeyReleased(evt);
            }
        });

        jLabel18.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 52));
        jLabel18.setToolTipText(language_main_frame.LangLabel(constants.getLanguage_option(), 53));

        grid1.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 55));
        grid1.setToolTipText(language_main_frame.LangLabel(constants.getLanguage_option(), 56));
        grid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grid1ActionPerformed(evt);
            }
        });

        jLabel19.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 57));

        jTextField_pocdes.setText("jTextField1");
        jTextField_pocdes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_pocdesActionPerformed(evt);
            }
        });
        jTextField_pocdes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_pocdesKeyReleased(evt);
            }
        });

        jLabel20.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 58));

        jButton1.setText("Test 2D");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Test 1D");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField_sizeX.setText("jTextField1");
        jTextField_sizeX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_sizeXKeyReleased(evt);
            }
        });

        jLabel6.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 33));

        jTextField_sizeY.setText("jTextField1");
        jTextField_sizeY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_sizeYKeyReleased(evt);
            }
        });

        jLabel7.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 34));

        jTextField_stepX.setText("jTextField1");
        jTextField_stepX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_stepXKeyReleased(evt);
            }
        });

        jLabel5.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 31));
        jLabel5.setToolTipText(language_main_frame.LangLabel(constants.getLanguage_option(), 32));

        jTextField_stepZ.setText("jTextField1");
        jTextField_stepZ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_stepZKeyReleased(evt);
            }
        });

        jTextField_stepY.setText("jTextField1");
        jTextField_stepY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_stepYKeyReleased(evt);
            }
        });

        jLabel4.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 29));
        jLabel4.setToolTipText(language_main_frame.LangLabel(constants.getLanguage_option(), 30));

        jLabel2.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 27));
        jLabel2.setToolTipText(language_main_frame.LangLabel(constants.getLanguage_option(), 28));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_sizeX)
                            .addComponent(jTextField_sizeY, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField_stepX, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_stepY)
                            .addComponent(jTextField_stepZ, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_sizeX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_sizeY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_stepX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_stepY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_stepZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField_hrubkaTA.setText("jTextField1");
        jTextField_hrubkaTA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_hrubkaTAKeyReleased(evt);
            }
        });

        jLabel8.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 35));
        jLabel8.setToolTipText(language_main_frame.LangLabel(constants.getLanguage_option(), 36));

        jTextField_hrubkaTB.setText("jTextField1");
        jTextField_hrubkaTB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_hrubkaTBKeyReleased(evt);
            }
        });

        jLabel9.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 37));
        jLabel9.setToolTipText(language_main_frame.LangLabel(constants.getLanguage_option(), 38));

        jTextField_grid.setText("jTextField1");
        jTextField_grid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_gridKeyReleased(evt);
            }
        });

        jLabel12.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 43));

        jTextField_nasUP.setText("jTextField1");
        jTextField_nasUP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_nasUPKeyReleased(evt);
            }
        });

        jLabel13.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 44));
        jLabel13.setToolTipText(language_main_frame.LangLabel(constants.getLanguage_option(), 45));

        jTextField_nasDown.setText("jTextField1");
        jTextField_nasDown.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_nasDownKeyReleased(evt);
            }
        });

        jLabel14.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 46));
        jLabel14.setToolTipText(language_main_frame.LangLabel(constants.getLanguage_option(), 47));

        jTextField_nassides.setText("jTextField1");
        jTextField_nassides.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_nassidesKeyReleased(evt);
            }
        });

        jLabel15.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 48));
        jLabel15.setToolTipText(language_main_frame.LangLabel(constants.getLanguage_option(), 49));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_nasDown, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(jTextField_nasUP)
                            .addComponent(jTextField_nassides))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField_grid)
                            .addComponent(jTextField_hrubkaTB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_hrubkaTA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_hrubkaTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_hrubkaTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_grid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_nasUP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_nasDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_nassides, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField_pockon.setText("jTextField1");
        jTextField_pockon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_pockonActionPerformed(evt);
            }
        });
        jTextField_pockon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_pockonKeyReleased(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/images.jpg"))); // NOI18N

        ROW1.setText("jTextField1");
        ROW1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ROW1ActionPerformed(evt);
            }
        });
        ROW1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ROW1KeyReleased(evt);
            }
        });

        ROW2.setText("jTextField1");
        ROW2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ROW2KeyReleased(evt);
            }
        });

        jLabel22.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 67));

        jLabel23.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 68));

        noZA.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 94));
        noZA.setToolTipText(language_main_frame.LangLabel(constants.getLanguage_option(), 95));
        noZA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noZAActionPerformed(evt);
            }
        });

        buttonGroup2.add(RAIN);
        RAIN.setSelected(true);
        RAIN.setText("RAIN");

        buttonGroup2.add(TEMP);
        TEMP.setText("TEMP");
        TEMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEMPActionPerformed(evt);
            }
        });

        buttonGroup2.add(BW);
        BW.setText("BW");
        BW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BWActionPerformed(evt);
            }
        });

        buttonGroup2.add(COL2);
        COL2.setText("COL2");

        jLabel24.setText("farebna schéma");

        jLabel25.setText("Zscale limit");

        ZcaleMax.setText("5000");
        ZcaleMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZcaleMaxActionPerformed(evt);
            }
        });

        ZscaleMin.setText("-5000");

        jLabel26.setText("Max");

        jLabel27.setText("Min");

        AXtype.setText("AX type: true rect /false auto");
        AXtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AXtypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(grid, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(grid1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addContainerGap())
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jTextField_popisX, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jTextField_hrubkaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jTextField_popisZ, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jTextField_hrubkaCA, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField_popisY, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField_pockon, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField_pocdes, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(AXtype, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(noZA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ROW1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                                    .addComponent(ROW2))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RAIN)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TEMP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BW)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(COL2))
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ZcaleMax, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel26)
                                        .addGap(7, 7, 7)
                                        .addComponent(ZscaleMin, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel27)))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_pocdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_pockon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_popisX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_popisZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_popisY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_hrubkaCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_hrubkaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grid)
                            .addComponent(grid1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AXtype)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noZA)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ROW1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ROW2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RAIN)
                    .addComponent(TEMP)
                    .addComponent(BW)
                    .addComponent(COL2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZcaleMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZscaleMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void seticon() {
     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/graphics/" + "icon.png")));
    }
    private void gridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gridActionPerformed
        constants.setDislin_grid(grid.isSelected());
    }//GEN-LAST:event_gridActionPerformed

    private void jTextField_stepXKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_stepXKeyReleased
        constants.setDislin_Step_between_the_labels_X(  (int) help.ReadCheckDouble(jTextField_stepX , 10));
    }//GEN-LAST:event_jTextField_stepXKeyReleased

    private void jTextField_stepYKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_stepYKeyReleased
         constants.setDislin_Step_between_the_labels_Y(  (int) help.ReadCheckDouble(jTextField_stepY , 10));
    }//GEN-LAST:event_jTextField_stepYKeyReleased

    private void jTextField_stepZKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_stepZKeyReleased
        constants.setDislin_Step_between_the_labels_Z(  (int) help.ReadCheckDouble(jTextField_stepZ , 5));
    }//GEN-LAST:event_jTextField_stepZKeyReleased

    private void jTextField_sizeXKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_sizeXKeyReleased
         constants.setDislin_velkost_strany_X((int) help.ReadCheckDouble(jTextField_sizeX , 6000));
    }//GEN-LAST:event_jTextField_sizeXKeyReleased

    private void jTextField_sizeYKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_sizeYKeyReleased
        constants.setDislin_velkost_strany_Y((int) help.ReadCheckDouble(jTextField_sizeY , 4000));
    }//GEN-LAST:event_jTextField_sizeYKeyReleased

    private void jTextField_hrubkaTAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_hrubkaTAKeyReleased
       constants.setDislin_velkost_textu_pred_grafom((int) help.ReadCheckDouble(jTextField_hrubkaTA , 70));
    }//GEN-LAST:event_jTextField_hrubkaTAKeyReleased

    private void jTextField_hrubkaTBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_hrubkaTBKeyReleased
        constants.setDislin_velkost_textu_za_grafom((int) help.ReadCheckDouble(jTextField_hrubkaTB , 70));
    }//GEN-LAST:event_jTextField_hrubkaTBKeyReleased

    private void jTextField_hrubkaCAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_hrubkaCAKeyReleased
         constants.setDislin_hrubka_ciar_pred_grafom((int) help.ReadCheckDouble(jTextField_hrubkaCA , 8));
    }//GEN-LAST:event_jTextField_hrubkaCAKeyReleased

    private void jTextField_hrubkaCBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_hrubkaCBKeyReleased
        constants.setDislin_hrubka_ciar_za_grafom((int) help.ReadCheckDouble(jTextField_hrubkaCA , 5));
    }//GEN-LAST:event_jTextField_hrubkaCBKeyReleased

    private void jTextField_gridKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_gridKeyReleased
        constants.setDislin_hrubka_ciar_GRID((int) help.ReadCheckDouble(jTextField_grid , 8));
    }//GEN-LAST:event_jTextField_gridKeyReleased

    private void jTextField_nasUPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nasUPKeyReleased
        constants.setDislin_graph_nasobok_z_vrchu((float) help.ReadCheckDouble(jTextField_nasUP , 1.2));
    }//GEN-LAST:event_jTextField_nasUPKeyReleased

    private void jTextField_nasDownKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nasDownKeyReleased
        constants.setDislin_graph_nasobok_z_spodu((float) help.ReadCheckDouble(jTextField_nasDown , 1.2));
    }//GEN-LAST:event_jTextField_nasDownKeyReleased

    private void jTextField_nassidesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nassidesKeyReleased
        constants.setDislin_graph_nasobok_zo_stran((float) help.ReadCheckDouble(jTextField_nassides , 1.2));
    }//GEN-LAST:event_jTextField_nassidesKeyReleased

    private void jTextField_popisXKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_popisXKeyReleased
         constants.setDislin_Label_X(jTextField_popisX.getText() );
    }//GEN-LAST:event_jTextField_popisXKeyReleased

    private void jTextField_popisYKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_popisYKeyReleased
       constants.setDislin_Label_Y(jTextField_popisY.getText() );
    }//GEN-LAST:event_jTextField_popisYKeyReleased

    private void jTextField_popisZKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_popisZKeyReleased
       constants.setDislin_Label_Z(jTextField_popisZ.getText() );
    }//GEN-LAST:event_jTextField_popisZKeyReleased

    private void grid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grid1ActionPerformed
        constants.setDislin_graph_bgcol(grid1.isSelected());
    }//GEN-LAST:event_grid1ActionPerformed

    private void jTextField_pockonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_pockonKeyReleased
        constants.setDislin_pocet_kontur((int) help.ReadCheckDouble(jTextField_pockon , 9));
    }//GEN-LAST:event_jTextField_pockonKeyReleased

    private void jTextField_pocdesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_pocdesKeyReleased
         constants.setDislin_pocet_des_miest((int) help.ReadCheckDouble(jTextField_pocdes , 2));
    }//GEN-LAST:event_jTextField_pocdesKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
        
        
      double[] xray = new double[]{-2,1,0,-1,-2};
      double[] xray2 = new double[]{3,5,2,5,2};
      String[] xray3 = new String[]{"va1 1","val 2"};
      ArrayList<double[]> yray = new ArrayList<double[]>();
      
      yray.add(xray);
      yray.add(xray2);
      
     plot_1D graf2 = new plot_1D( xray,yray, constants.getDislin_Label_X(), constants.getDislin_Label_Y(), "Testing", "1D graph", xray3);          
     graf2.setScreen(true);
     
     graf2.setFile(false,"");
        try {
            graf2.draw_1D_yn();
        } catch (IOException ex) {
            Logger.getLogger(Dislin_Settings.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField_hrubkaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_hrubkaCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_hrubkaCBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double[] xray = new double[]{-2,1,0,-1,-2};
      
      
      
      plot_2D graf3 = new plot_2D(xray,xray,xray,constants.getDislin_Label_X(),constants.getDislin_Label_Z(),"Testing", "2D graph contour",true, true,false,true);
        graf3.setScreen(true);          
        graf3.setFile(false,"" );
        try {
            graf3.draw_2D_yn(); // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(Dislin_Settings.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         graf3 = new plot_2D(xray,xray,xray,constants.getDislin_Label_X(),constants.getDislin_Label_Z(),"Testing", "2D graph full",true, true,true,false);
        graf3.setScreen(true);          
        graf3.setFile(false,"" );
        try {
            graf3.draw_2D_yn(); // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(Dislin_Settings.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField_pockonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_pockonActionPerformed
        
         
        
    }//GEN-LAST:event_jTextField_pockonActionPerformed

    private void jTextField_pocdesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_pocdesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_pocdesActionPerformed

    private void ROW1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ROW1ActionPerformed
       
    }//GEN-LAST:event_ROW1ActionPerformed

    private void ROW1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ROW1KeyReleased
       constants.setROW1(ROW1.getText());
    }//GEN-LAST:event_ROW1KeyReleased

    private void ROW2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ROW2KeyReleased
       constants.setROW2(ROW2.getText());
    }//GEN-LAST:event_ROW2KeyReleased

    private void noZAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noZAActionPerformed
        constants.setDislin_nozeroYA(noZA.isSelected());
    }//GEN-LAST:event_noZAActionPerformed

    static public JCheckBox getBW() {
        return BW;
    }

    public void setBW(JCheckBox BW) {
        this.BW = BW;
    }

    static public JCheckBox getCOL2() {
        return COL2;
    }

    public void setCOL2(JCheckBox COL2) {
        this.COL2 = COL2;
    }

   static  public JCheckBox getRAIN() {
        return RAIN;
    }

    public void setRAIN(JCheckBox RAIN) {
        this.RAIN = RAIN;
    }

   static public JCheckBox getTEMP() {
        return TEMP;
    }

    public void setTEMP(JCheckBox TEMP) {
        this.TEMP = TEMP;
    }

    static public JTextField getZcaleMax() {
        return ZcaleMax;
    }

    public void setZcaleMax(JTextField ZcaleMax) {
        this.ZcaleMax = ZcaleMax;
    }

    public static JCheckBox getAXtype() {
        return AXtype;
    }

    public static void setAXtype(JCheckBox AXtype) {
        Dislin_Settings.AXtype = AXtype;
    }

    static public JTextField getZscaleMin() {
        return ZscaleMin;
    }

    public void setZscaleMin(JTextField ZscaleMin) {
        this.ZscaleMin = ZscaleMin;
    }

    private void TEMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEMPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEMPActionPerformed

    private void BWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BWActionPerformed

    private void ZcaleMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZcaleMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZcaleMaxActionPerformed

    private void AXtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AXtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AXtypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dislin_Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dislin_Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dislin_Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dislin_Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dislin_Settings().setVisible(true);
            }
        });
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JCheckBox AXtype;
    private static javax.swing.JCheckBox BW;
    private static javax.swing.JCheckBox COL2;
    private static javax.swing.JCheckBox RAIN;
    private javax.swing.JTextField ROW1;
    private javax.swing.JTextField ROW2;
    private static javax.swing.JCheckBox TEMP;
    private static javax.swing.JTextField ZcaleMax;
    private static javax.swing.JTextField ZscaleMin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private static javax.swing.JCheckBox grid;
    private static javax.swing.JCheckBox grid1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField_grid;
    private javax.swing.JTextField jTextField_hrubkaCA;
    private javax.swing.JTextField jTextField_hrubkaCB;
    private javax.swing.JTextField jTextField_hrubkaTA;
    private javax.swing.JTextField jTextField_hrubkaTB;
    private javax.swing.JTextField jTextField_nasDown;
    private javax.swing.JTextField jTextField_nasUP;
    private javax.swing.JTextField jTextField_nassides;
    private javax.swing.JTextField jTextField_pocdes;
    private javax.swing.JTextField jTextField_pockon;
    private javax.swing.JTextField jTextField_popisX;
    private javax.swing.JTextField jTextField_popisY;
    private javax.swing.JTextField jTextField_popisZ;
    private javax.swing.JTextField jTextField_sizeX;
    private javax.swing.JTextField jTextField_sizeY;
    private javax.swing.JTextField jTextField_stepX;
    private javax.swing.JTextField jTextField_stepY;
    private javax.swing.JTextField jTextField_stepZ;
    private static javax.swing.JCheckBox noZA;
    // End of variables declaration//GEN-END:variables
    public static boolean about_JframeIsOpen;

    
}
