/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emft_vol2;

import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JCheckBox;

/**
 *
 * @author Jozef
 */
public class TxT_JFrame extends javax.swing.JFrame {

    /**
     * Creates new form about_JFrame
     */
    public TxT_JFrame() {
        initComponents();
        seticon();
        setLocationRelativeTo(null);
        about_JframeIsOpen=true;
         addWindowListener(new WindowAdapter() // listener na krizik zabretie okna
        {
            @Override
            public void windowClosing(WindowEvent e)
            {
                about_JframeIsOpen= false;
                e.getWindow().dispose();
            }
        });
        
    }

    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        B_COMPLEX = new javax.swing.JCheckBox();
        B_RMS1 = new javax.swing.JCheckBox();
        B_PHASOR = new javax.swing.JCheckBox();
        B_XYZ_RMS = new javax.swing.JCheckBox();
        B_XYZ_COMPLEX = new javax.swing.JCheckBox();
        B_XYZ_PHASOR = new javax.swing.JCheckBox();
        E_RMS = new javax.swing.JCheckBox();
        E_PHASOR = new javax.swing.JCheckBox();
        E_COMPLEX = new javax.swing.JCheckBox();
        E_XYZ_RMS = new javax.swing.JCheckBox();
        E_XYZ_COMPLEX = new javax.swing.JCheckBox();
        E_XYZ_PHASOR = new javax.swing.JCheckBox();
        B_GeoMat = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        I_RMS = new javax.swing.JCheckBox();
        I_XYZ_PHASOR = new javax.swing.JCheckBox();
        I_COMPLEX = new javax.swing.JCheckBox();
        I_XYZ_COMPLEX = new javax.swing.JCheckBox();
        I_XYZ_RMS = new javax.swing.JCheckBox();
        I_PHASOR = new javax.swing.JCheckBox();
        Emod_COMPLEX = new javax.swing.JCheckBox();
        Emod_XYZ_COMPLEX = new javax.swing.JCheckBox();
        Emod_XYZ_RMS = new javax.swing.JCheckBox();
        Emod_PHASOR = new javax.swing.JCheckBox();
        Emod_RMS = new javax.swing.JCheckBox();
        Emod_XYZ_PHASOR = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        if(constants.getLanguage_option() ==1){
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/header_txt.png"))); // NOI18N
        }
        if(constants.getLanguage_option() ==3){
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/header_txt.png"))); // NOI18N
        }
        if(constants.getLanguage_option() ==2){
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/header_txt.png"))); // NOI18N
        }

        jLabel2.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 12));

        B_COMPLEX.setText("B complex");
        B_COMPLEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_COMPLEXActionPerformed(evt);
            }
        });

        B_RMS1.setSelected(true);
        B_RMS1.setText("B rms");
        B_RMS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_RMS1ActionPerformed(evt);
            }
        });

        B_PHASOR.setText("B phasor");
        B_PHASOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_PHASORActionPerformed(evt);
            }
        });

        B_XYZ_RMS.setText("B xyz rms");
        B_XYZ_RMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_XYZ_RMSActionPerformed(evt);
            }
        });

        B_XYZ_COMPLEX.setText("B  xyz complex");
        B_XYZ_COMPLEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_XYZ_COMPLEXActionPerformed(evt);
            }
        });

        B_XYZ_PHASOR.setText("B  xyz phasor");
        B_XYZ_PHASOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_XYZ_PHASORActionPerformed(evt);
            }
        });

        E_RMS.setSelected(true);
        E_RMS.setText("E rms");
        E_RMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_RMSActionPerformed(evt);
            }
        });

        E_PHASOR.setText("E phasor");
        E_PHASOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_PHASORActionPerformed(evt);
            }
        });

        E_COMPLEX.setText("E complex");
        E_COMPLEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_COMPLEXActionPerformed(evt);
            }
        });

        E_XYZ_RMS.setText("E xyz rms");
        E_XYZ_RMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_XYZ_RMSActionPerformed(evt);
            }
        });

        E_XYZ_COMPLEX.setText("E  xyz complex");
        E_XYZ_COMPLEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_XYZ_COMPLEXActionPerformed(evt);
            }
        });

        E_XYZ_PHASOR.setText("E  xyz phasor");
        E_XYZ_PHASOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_XYZ_PHASORActionPerformed(evt);
            }
        });

        B_GeoMat.setText("B  GeoMat");
        B_GeoMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_GeoMatActionPerformed(evt);
            }
        });

        jLabel3.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 11));

        jLabel4.setText(language_main_frame.LangLabel(constants.getLanguage_option(), 12));

        I_RMS.setSelected(true);
        I_RMS.setText("I rms");
        I_RMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_RMSActionPerformed(evt);
            }
        });

        I_XYZ_PHASOR.setText("I  xyz phasor");
        I_XYZ_PHASOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_XYZ_PHASORActionPerformed(evt);
            }
        });

        I_COMPLEX.setText("I complex");
        I_COMPLEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_COMPLEXActionPerformed(evt);
            }
        });

        I_XYZ_COMPLEX.setText("I  xyz complex");
        I_XYZ_COMPLEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_XYZ_COMPLEXActionPerformed(evt);
            }
        });

        I_XYZ_RMS.setText("I xyz rms");
        I_XYZ_RMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_XYZ_RMSActionPerformed(evt);
            }
        });

        I_PHASOR.setText("I phasor");
        I_PHASOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_PHASORActionPerformed(evt);
            }
        });

        Emod_COMPLEX.setText("Emod complex");
        Emod_COMPLEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emod_COMPLEXActionPerformed(evt);
            }
        });

        Emod_XYZ_COMPLEX.setText("Emod  xyz complex");
        Emod_XYZ_COMPLEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emod_XYZ_COMPLEXActionPerformed(evt);
            }
        });

        Emod_XYZ_RMS.setText("Emod xyz rms");
        Emod_XYZ_RMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emod_XYZ_RMSActionPerformed(evt);
            }
        });

        Emod_PHASOR.setText("Emod phasor");
        Emod_PHASOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emod_PHASORActionPerformed(evt);
            }
        });

        Emod_RMS.setSelected(true);
        Emod_RMS.setText("Emod rms");
        Emod_RMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emod_RMSActionPerformed(evt);
            }
        });

        Emod_XYZ_PHASOR.setText("Emod  xyz phasor");
        Emod_XYZ_PHASOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emod_XYZ_PHASORActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(E_RMS, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(E_XYZ_RMS, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(E_COMPLEX))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(E_XYZ_COMPLEX))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(B_XYZ_RMS)
                                            .addComponent(B_RMS1))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(B_XYZ_COMPLEX)
                                            .addComponent(B_COMPLEX))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(E_PHASOR)
                                    .addComponent(B_XYZ_PHASOR)
                                    .addComponent(E_XYZ_PHASOR)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(B_PHASOR)
                                        .addGap(34, 34, 34)
                                        .addComponent(B_GeoMat))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(I_RMS, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(I_XYZ_RMS, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(I_COMPLEX))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(I_XYZ_COMPLEX)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(I_PHASOR)
                                    .addComponent(I_XYZ_PHASOR)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Emod_RMS, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Emod_XYZ_RMS, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(Emod_COMPLEX))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(Emod_XYZ_COMPLEX)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Emod_PHASOR)
                                    .addComponent(Emod_XYZ_PHASOR))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_RMS1)
                    .addComponent(B_COMPLEX)
                    .addComponent(B_PHASOR)
                    .addComponent(B_GeoMat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_XYZ_RMS)
                    .addComponent(B_XYZ_COMPLEX)
                    .addComponent(B_XYZ_PHASOR))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E_RMS)
                    .addComponent(E_COMPLEX)
                    .addComponent(E_PHASOR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E_XYZ_RMS)
                    .addComponent(E_XYZ_COMPLEX)
                    .addComponent(E_XYZ_PHASOR))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(I_RMS)
                    .addComponent(I_COMPLEX)
                    .addComponent(I_PHASOR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(I_XYZ_RMS)
                    .addComponent(I_XYZ_COMPLEX)
                    .addComponent(I_XYZ_PHASOR))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Emod_RMS)
                    .addComponent(Emod_COMPLEX)
                    .addComponent(Emod_PHASOR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Emod_XYZ_RMS)
                    .addComponent(Emod_XYZ_COMPLEX)
                    .addComponent(Emod_XYZ_PHASOR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void seticon() {
     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/graphics/" + "icon.png")));
    }
    private void B_COMPLEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_COMPLEXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_COMPLEXActionPerformed

    private void B_RMS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_RMS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_RMS1ActionPerformed

    private void B_PHASORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_PHASORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_PHASORActionPerformed

    private void B_XYZ_RMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_XYZ_RMSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_XYZ_RMSActionPerformed

    private void B_XYZ_COMPLEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_XYZ_COMPLEXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_XYZ_COMPLEXActionPerformed

    private void B_XYZ_PHASORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_XYZ_PHASORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_XYZ_PHASORActionPerformed

    private void E_RMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_RMSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E_RMSActionPerformed

    private void E_PHASORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_PHASORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E_PHASORActionPerformed

    private void E_COMPLEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_COMPLEXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E_COMPLEXActionPerformed

    private void E_XYZ_RMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_XYZ_RMSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E_XYZ_RMSActionPerformed

    private void E_XYZ_COMPLEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_XYZ_COMPLEXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E_XYZ_COMPLEXActionPerformed

    private void E_XYZ_PHASORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_XYZ_PHASORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E_XYZ_PHASORActionPerformed

    private void B_GeoMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_GeoMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_GeoMatActionPerformed

    private void I_RMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_RMSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_I_RMSActionPerformed

    private void I_XYZ_PHASORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_XYZ_PHASORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_I_XYZ_PHASORActionPerformed

    private void I_COMPLEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_COMPLEXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_I_COMPLEXActionPerformed

    private void I_XYZ_COMPLEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_XYZ_COMPLEXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_I_XYZ_COMPLEXActionPerformed

    private void I_XYZ_RMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_XYZ_RMSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_I_XYZ_RMSActionPerformed

    private void I_PHASORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_PHASORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_I_PHASORActionPerformed

    private void Emod_COMPLEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emod_COMPLEXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Emod_COMPLEXActionPerformed

    private void Emod_XYZ_COMPLEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emod_XYZ_COMPLEXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Emod_XYZ_COMPLEXActionPerformed

    private void Emod_XYZ_RMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emod_XYZ_RMSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Emod_XYZ_RMSActionPerformed

    private void Emod_PHASORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emod_PHASORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Emod_PHASORActionPerformed

    private void Emod_RMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emod_RMSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Emod_RMSActionPerformed

    private void Emod_XYZ_PHASORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emod_XYZ_PHASORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Emod_XYZ_PHASORActionPerformed

    public static JCheckBox getB_COMPLEX() {
        return B_COMPLEX;
    }

    public  static JCheckBox getB_GeoMat() {
        return B_GeoMat;
    }

    public  static JCheckBox getB_PHASOR() {
        return B_PHASOR;
    }

    public static JCheckBox getB_RMS1() {
        return B_RMS1;
    }

    public static JCheckBox getB_XYZ_COMPLEX() {
        return B_XYZ_COMPLEX;
    }

    public static JCheckBox getB_XYZ_PHASOR() {
        return B_XYZ_PHASOR;
    }

    public static JCheckBox getB_XYZ_RMS() {
        return B_XYZ_RMS;
    }

    public static JCheckBox getE_COMPLEX() {
        return E_COMPLEX;
    }

    public static JCheckBox getE_PHASOR() {
        return E_PHASOR;
    }

    public static JCheckBox getE_RMS() {
        return E_RMS;
    }

    public static JCheckBox getE_XYZ_COMPLEX() {
        return E_XYZ_COMPLEX;
    }

    public static JCheckBox getE_XYZ_PHASOR() {
        return E_XYZ_PHASOR;
    }

    public static JCheckBox getE_XYZ_RMS() {
        return E_XYZ_RMS;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TxT_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TxT_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TxT_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TxT_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TxT_JFrame().setVisible(true);
            }
        });
         
    }

    public static JCheckBox getEmod_COMPLEX() {
        return Emod_COMPLEX;
    }

    public static void setEmod_COMPLEX(JCheckBox Emod_COMPLEX) {
        TxT_JFrame.Emod_COMPLEX = Emod_COMPLEX;
    }

    public static JCheckBox getEmod_PHASOR() {
        return Emod_PHASOR;
    }

    public static void setEmod_PHASOR(JCheckBox Emod_PHASOR) {
        TxT_JFrame.Emod_PHASOR = Emod_PHASOR;
    }

    public static JCheckBox getEmod_RMS() {
        return Emod_RMS;
    }

    public static void setEmod_RMS(JCheckBox Emod_RMS) {
        TxT_JFrame.Emod_RMS = Emod_RMS;
    }

    public static JCheckBox getEmod_XYZ_COMPLEX() {
        return Emod_XYZ_COMPLEX;
    }

    public static void setEmod_XYZ_COMPLEX(JCheckBox Emod_XYZ_COMPLEX) {
        TxT_JFrame.Emod_XYZ_COMPLEX = Emod_XYZ_COMPLEX;
    }

    public static JCheckBox getEmod_XYZ_PHASOR() {
        return Emod_XYZ_PHASOR;
    }

    public static void setEmod_XYZ_PHASOR(JCheckBox Emod_XYZ_PHASOR) {
        TxT_JFrame.Emod_XYZ_PHASOR = Emod_XYZ_PHASOR;
    }

    public static JCheckBox getEmod_XYZ_RMS() {
        return Emod_XYZ_RMS;
    }

    public static void setEmod_XYZ_RMS(JCheckBox Emod_XYZ_RMS) {
        TxT_JFrame.Emod_XYZ_RMS = Emod_XYZ_RMS;
    }

    public static JCheckBox getI_COMPLEX() {
        return I_COMPLEX;
    }

    public static void setI_COMPLEX(JCheckBox I_COMPLEX) {
        TxT_JFrame.I_COMPLEX = I_COMPLEX;
    }

    public static JCheckBox getI_PHASOR() {
        return I_PHASOR;
    }

    public static void setI_PHASOR(JCheckBox I_PHASOR) {
        TxT_JFrame.I_PHASOR = I_PHASOR;
    }

    public static JCheckBox getI_RMS() {
        return I_RMS;
    }

    public static void setI_RMS(JCheckBox I_RMS) {
        TxT_JFrame.I_RMS = I_RMS;
    }

    public static JCheckBox getI_XYZ_COMPLEX() {
        return I_XYZ_COMPLEX;
    }

    public static void setI_XYZ_COMPLEX(JCheckBox I_XYZ_COMPLEX) {
        TxT_JFrame.I_XYZ_COMPLEX = I_XYZ_COMPLEX;
    }

    public static JCheckBox getI_XYZ_PHASOR() {
        return I_XYZ_PHASOR;
    }

    public static void setI_XYZ_PHASOR(JCheckBox I_XYZ_PHASOR) {
        TxT_JFrame.I_XYZ_PHASOR = I_XYZ_PHASOR;
    }

    public static JCheckBox getI_XYZ_RMS() {
        return I_XYZ_RMS;
    }

    public static void setI_XYZ_RMS(JCheckBox I_XYZ_RMS) {
        TxT_JFrame.I_XYZ_RMS = I_XYZ_RMS;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JCheckBox B_COMPLEX;
    private static javax.swing.JCheckBox B_GeoMat;
    private static javax.swing.JCheckBox B_PHASOR;
    private static javax.swing.JCheckBox B_RMS1;
    private static javax.swing.JCheckBox B_XYZ_COMPLEX;
    private static javax.swing.JCheckBox B_XYZ_PHASOR;
    private static javax.swing.JCheckBox B_XYZ_RMS;
    private static javax.swing.JCheckBox E_COMPLEX;
    private static javax.swing.JCheckBox E_PHASOR;
    private static javax.swing.JCheckBox E_RMS;
    private static javax.swing.JCheckBox E_XYZ_COMPLEX;
    private static javax.swing.JCheckBox E_XYZ_PHASOR;
    private static javax.swing.JCheckBox E_XYZ_RMS;
    private static javax.swing.JCheckBox Emod_COMPLEX;
    private static javax.swing.JCheckBox Emod_PHASOR;
    private static javax.swing.JCheckBox Emod_RMS;
    private static javax.swing.JCheckBox Emod_XYZ_COMPLEX;
    private static javax.swing.JCheckBox Emod_XYZ_PHASOR;
    private static javax.swing.JCheckBox Emod_XYZ_RMS;
    private static javax.swing.JCheckBox I_COMPLEX;
    private static javax.swing.JCheckBox I_PHASOR;
    private static javax.swing.JCheckBox I_RMS;
    private static javax.swing.JCheckBox I_XYZ_COMPLEX;
    private static javax.swing.JCheckBox I_XYZ_PHASOR;
    private static javax.swing.JCheckBox I_XYZ_RMS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
    public static boolean about_JframeIsOpen;

    
}
